 /*================================================
  * Arduino program for muDAQ
  * Created:       2022-05-09
  * Last Modified: 2022-05-22
  * By: Joseph Lewis-Merrill
  * 
  * Description: 
  *    Manages Arduino board for reading selected ADC channels and
  *    transmits that information via serial. Accepts commands
  *    via serial from controller program.
  *    
  * Special thanks to Jewel Abbate
  *==================================================
  */


#include "primary_fncs.h"
#include "base_fncs.h"


/*--------------------------------------------------
 * Type: Struct
 * struct daq_settings global_settings
 *  Holds settings and data generated by the program
 *  Created by setup_loop(), passed to main_loop()
 *  Declared in base_fncs.h
 *  Recreated when main_loop() signals for a restart
 *--------------------------------------------------
 */
struct daq_settings global_daq_settings;

/*--------------------------------------------------
 * Type: Function
 * void setup()
 *  Called once automatically on program start
 *  Called again if main_loop signals for a restart
 *  
 *  Arguments:
 *    None
 *    
 *  Returns
 *    None
 *--------------------------------------------------
 */
void setup() {
  global_daq_settings = setup_loop();
}


/*--------------------------------------------------
 * Type: function
 * void loop()
 *  Called repeated (as if by a while(true) loop)
 *    while the program is running.
 *  
 *  Arguments:
 *    None
 *    
 *  Returns
 *    None
 *--------------------------------------------------
 */
void loop() {
  if (main_loop(&global_daq_settings)){
    setup();
  }
}
